- name: Install tools Play
  hosts: localhost
  tasks:
  - name: install vim, tmux, git, socat
    action: >
     {{ ansible_pkg_mgr }} name={{ item }} state=present
    with_items:
     - vim
     - tmux
     - socat
     - git
    become: true
    become_user: root
    when: (ansible_os_family != "Darwin")
  - name: install vim, tmux, git, socat
    action: >
     {{ ansible_pkg_mgr }} name={{ item }} state=present
    with_items:
     - vim
     - tmux
     - socat
     - git
    when: (ansible_os_family == "Darwin")
  - name: update pip to latest
    pip:
      name: pip
      state: latest
    become: true
    become_user: root
  - name: install dep python packages 
    pip:
      name: "{{ item }}"
    with_items:
     - psutil
     - bzr
     - pyuv
     - i3ipc
     - powerline-status
    become: true
    become_user: root

- name: Fonts Configuration Play
  hosts: localhost
  tasks:
    - block:
       - file: path=~/.local/share/fonts/ state=directory
       - copy:
          src: PowerlineSymbols.otf
          dest: ~/.local/share/fonts/
       - shell: fc-cache -vf ~/.local/share/fonts/
      when: (ansible_os_family != "Darwin")
    - block: 
      - git:
          repo: https://github.com/powerline/fonts.git
          dest: /tmp
      - script: /tmp/fonts/install.sh
      become: true
      become_user: root
      when: (ansible_os_family == "Darwin")
    - block:
       - file: path=~/.config/fontconfig/conf.d/ state=directory
       - copy:
          src: 10-powerline-symbols.conf
          dest: ~/.config/fontconfig/conf.d/
      become: true
      become_user: root

- name: Copy configurations to "~" directory
  hosts: localhost
  gather_facts: False
  tasks:
    - git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim
    - copy:
       src: .vimrc
       dest: ~/
    - copy:
       src: .tmux.conf
       dest: ~/
    - shell: vim +PluginInstall +qall
    - shell: pip show powerline-status 2>/dev/null | grep Location | awk '{print $2}'
      register: powerline_comm
    - lineinfile: dest=~/.bashrc line='export POWERLINE_PACKAGE_DIR={{ powerline_comm.stdout }}' insertafter='EOF' state=present
