---
- name: Install tools & dependency
  hosts: all
  roles:
    - install_common_tools
    - set_vim_flavour_fact
    - install_vim_flavour
    - install_pip_packages

- name: Install support for vim and tmux
  hosts: all
  gather_facts: False
  roles:
    - install_vundle
    - install_tpm

- name: Fonts Configuration
  hosts: all
  gather_facts: False
  roles:
    - install_powerline_fonts

- name: Copy configurations & Install Plugins
  hosts: all
  roles:
    - install_vim_plugin_n_config
    - install_vim_command_t
    - install_tmux_plugin_n_config
