- name: Install tools Play
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: Install tmux, git, socat
    action: >
     {{ ansible_pkg_mgr }} name={{ item }} state=present
    with_items:
     - tmux
     - socat
     - git
  - set_fact:
         vim_flavour: "vim" 
  - name: Overrite vim version for Debian
    set_fact:
      vim_flavour: "vim-gnome" 
    when: (ansible_os_family == "Debian")
  - name: Install Vim
    action: >
     {{ ansible_pkg_mgr }} name={{ vim_flavour }} state=present
  - name: update pip to latest
    pip:
      name: pip
      state: latest
  - name: install dep python packages 
    pip:
      name: "{{ item }}"
    with_items:
     - psutil
     - bzr
     - pyuv
     - i3ipc
     - powerline-status
  - name: Installing Vundle for vim 
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim

- name: Fonts Configuration Play
  hosts: all
  tasks:
    - block:
       - file: path=~/.local/share/fonts/ state=directory
       - copy:
          src: PowerlineSymbols.otf
          dest: ~/.local/share/fonts/
       - shell: fc-cache -vf ~/.local/share/fonts/
    - block: 
      - file: path=~/tmp/fonts state=absent
      - git:
          repo: https://github.com/powerline/fonts.git
          dest: /tmp/fonts
      - script: /tmp/fonts/install.sh
    - block:
       - file: path=~/.config/fontconfig/conf.d/ state=directory
       - copy:
          src: 10-powerline-symbols.conf
          dest: ~/.config/fontconfig/conf.d/

- name: Copy configurations to "~" directory
  hosts: all
  gather_facts: False
  tasks:
    - copy:
       src: .vimrc
       dest: ~/
    - copy:
       src: .tmux.conf
       dest: ~/
    - shell: vim +PluginInstall +qall
    - shell: pip show powerline-status 2>/dev/null | grep Location | awk '{print $2}'
      register: powerline_comm
    - lineinfile: dest=~/.bashrc line='export POWERLINE_PACKAGE_DIR={{ powerline_comm.stdout }}' insertafter='EOF' state=present
