---
- name: Install Ruby-dev
  become: True
  action: >
      {{ ansible_pkg_mgr }} name="ruby-dev" state=present
  when: (ansible_distribution != "MacOSX")

- name: Install Vim on macOS
  shell: brew install ruby-build
  args:
    warn: no
  when: ( ansible_distribution == 'MacOSX' )

- name: make clean
  command: 'make clean'
  args:
    chdir: ~/.vim/bundle/command-t/ruby/command-t/ext/command-t
  ignore_errors: yes
- name: ruby extconf.rrb
  shell: 'ruby extconf.rb'
  args:
      chdir: ~/.vim/bundle/command-t/ruby/command-t/ext/command-t
- name: make
  make:
    chdir: ~/.vim/bundle/command-t/ruby/command-t/ext/command-t
