---
- name: Copy .tmux.conf
  copy:
      src: .tmux.conf
      dest: ~/
- name: Install tmux plugins
  shell: ~/.tmux/plugins/tpm/bin/install_plugins

- name: Detect powerline path
  shell: pip show powerline-status 2>/dev/null | grep Location | awk '{print $2}'
  register: powerline_comm

- name: Set Powerline package fact
  set_fact:
    P_P_D: "{{ powerline_comm.stdout }}"

- name: Add POWERLINE_PACKAGE_DIR env var to /etc/environment
  lineinfile: path=/etc/environment line='POWERLINE_PACKAGE_DIR={{ P_P_D }}' state=present
  when: ( ansible_distribution != 'MacOSX' )

- name: Add POWERLINE_PACKAGE_DIR env var to ~/.bashrc
  lineinfile: path=~/.bashrc line='export POWERLINE_PACKAGE_DIR={{ P_P_D }}' state=present create=yes

- name: Add POWERLINE_PACKAGE_DIR env var to ~/.bash_profile
  lineinfile: path=~/.bash_profile line='export POWERLINE_PACKAGE_DIR={{ P_P_D }}' state=present create=yes
