---
- name: update pip to latestw
  pip:
    name: pip
    state: latest
- name: Install dep python packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
   - psutil
   #- bzr #some how this package does not install need to check
   - pyuv
   - i3ipc
   - powerline-status
