---
- name: update pip to latest
  become: True
  pip:
    name: pip
    state: latest
  when: ( ansible_distribution != 'MacOSX' )
- name: Install dep python packages
  become: True
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
   - psutil
   - pyuv
   - i3ipc
   - powerline-status
  when: ( ansible_distribution != 'MacOSX' )

- name: update pip to latest
  pip:
    name: pip
    state: latest
  when: ( ansible_distribution == 'MacOSX' )
- name: Install dep python packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
   - psutil
   - pyuv
   - i3ipc
   - powerline-status
  when: ( ansible_distribution == 'MacOSX' )
