---
- name: Ubuntu - Install tmux, git, socat
  action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present
  with_items:
      - tmux
      - socat
      - git
  become: True
  #  when: ( ansible_distribution == 'Ubuntu' )
  #- name: MacOSX - Install tmux, git, socat
  #  action: >
  #      {{ ansible_pkg_mgr }} name={{ item }} state=present
  #  with_items:
  #      - tmux
  #      - socat
  #      - git
  #  when: ( ansible_distribution == 'MacOSX' )
