---
- name: Install Vim
  become_user: root
  action: >
      {{ ansible_pkg_mgr }} name={{ vim_flavour }} state=present
  when: ( ansible_distribution == 'Ubuntu' )
- name: Install Vim
  shell: brew install {{ vim_flavour }} --with-override-system-vim
  args:
    warn: no
  when: ( ansible_distribution == 'MacOSX' )
