---
- name: Install Vim
  become_user: root
  action: >
      {{ ansible_pkg_mgr }} name={{ vim_flavour }} state=present
  when: ( ansible_distribution == 'Ubuntu' )
- name: Install Vim
  action: >
      {{ ansible_pkg_mgr }} name={{ vim_flavour }} state=present
  when: ( ansible_distribution == 'MacOSX' )
