---
- name: Set vim flavour
  set_fact:
      vim_flavour: "vim"
- name: Overrite vim flavour for Debian
  set_fact:
      vim_flavour: "vim-gnome"
  when: (ansible_distribution == "Ubuntu")
- name: Overrite vim flavour for Debian
  set_fact:
      vim_flavour: "macvim"
  when: (ansible_distribution == "MacOSX")
